# Generated by Django 5.1.6 on 2025-06-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='upload_number',
            new_name='upload',
        ),
    ]
